### ISSUE TITLE
pip3 not supported for Ubuntu20

### ISSUE THREAD

**Issue by prowessandy** [cycloidio/ansible-base-aws#6]
Hello Authors, 
cc @talset  @gaelL 

We are deploying applications which require Ubuntu20, whose Cycloid pipeline will throw the error of "Unable to find any of pip3 to use.  pip needs to be installed."

Would you please do us the favour of modifying the code to survive both pip/pip3 and botocore alike so that we don't have to fork and customize the role? Thanks so much.

Andy

**Comment by talset** [comment]
@prowessandy I updated the role with a default_packages map which should solve the python/python3 package issue.

Let me know if by chance you can give it a try from `fl-pip3` branch

**Comment by prowessandy** [comment]
Hello @talset 
Thanks for the work! I tested it right now, but unfortunately, there's a 'variable undefined' error from the fl-pip3 branch. Will you please fix it ASAP? 

Error detail:
FAILED! => {"msg": "The conditional check 'setup_packages' failed. The error was: error while evaluating conditional (setup_packages): 'setup_packages' is undefined\n\nThe error appears to be in '/tmp/build/bc3b229a/ansible-playbook/roles/cycloidio.ansible-base-aws/tasks/deps.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install package depends | pre-setup\n  ^ here\n"}

**Comment by prowessandy** [comment]
Also, for the dictionary of 'default_packages,' I saw ubuntu16-19 and Debian 10 are included, but there's no ubuntu20. Can we make do with this design? Thanks so much.

**Comment by talset** [comment]
Sorry for the setup_packages missing var. It should be fixed.

Since ubuntu20 has no specific packages, it should ends up with `default(default_packages[ansible_os_family | lower]) ) + default_packages[ansible_os_family|lower + '-common']`

ubuntu ansible_os_family is Debian, so it should use `ansible_os_family[debian]` + `ansible_os_family[debian-common]`

Which is
```
        - rsync
        - tar
        - git-core
        - vim
        - jq
        - tmux
        - htop
        - unzip
        - telnet
        - ntp
        - locales
        - lsof
        - curl
        - zip
        - nfs-common
        - acl
        - apt-transport-https
        - python3
        - python3-pip
        - python3-boto3
        - python3-botocore
 
```

**Comment by prowessandy** [comment]
Hello @talset, 

Thanks for the fast response! I tested it again, the var error is gone, but the previous error returned.
FAILED! => {"changed": false, "msg": "Unable to find any of pip3 to use.  pip needs to be installed."}

I logged onto the instance and tried to "sudo apt install python3-pip" manually(last Friday and today), but it never worked. Instead, "sudo python3 install pip --upgrade pip" will do. Maybe 'apt' is no longer the proper way to install pip3?

Thanks again for your time!

**Comment by prowessandy** [comment]
sorry, the command I used was "sudo python3 -m pip install --upgrade pip"

**Comment by prowessandy** [comment]
Hi @talset 

Did you get time to review my message, or shall we go with 'sudo python3 -m pip install --upgrade pip' if the 'apt' module can no longer install pip3? Thanks!

**Comment by prowessandy** [comment]
Hi @talset , do you have a recommended ubuntu 20 AMI for the terraform stack in cycloid? Maybe should try a different AWS AMI. Thanks!

**Comment by talset** [comment]
Hi @prowessandy 

I'm going to create a dedicated ticket and add it to our planning. So we should be able to find a fix and check which AMI to use.
